### ISSUE TITLE
Clear() is throwing error "The handle is invalid." with .NET Core 6.0 and VisualStudio 2022

### ISSUE THREAD

**Issue by hguptauk** [mrlacey/VSConsole#17] opened 2022-04-26 22:36 UTC
at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.Clear()
   at System.Console.Clear()
   at VSConsole.Console.Clear()

![image](https://user-images.githubusercontent.com/44865520/165403850-56d84150-74d3-4d0e-977f-8ed2efe5720c.png)

**Comment by mrlacey** [comment] 2022-04-26 22:54
Hmmm. I can't repro with a simple app that has a project file that looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VSConsole" Version="1.0.0" />
  </ItemGroup>

</Project>
```

And using 17.2.0 preview 3.0

---

I'm curious to know if you can create a simple reproduction of the issue and which version of VS you have.

Also, looking at your code, what does `ConsoleExtension.Hide` do?

`VSConsole.Console.Clear()` is only [doing something really basic](https://github.com/mrlacey/VSConsole/blob/main/VSConsole.Lib/Console.cs#L50):

```cs
        public static void Clear()
        {
            System.Console.Clear();
            Debug.WriteLine($"{nameof(VSConsole)}-{nameof(Clear)}::");
        }
```

If you call `System.Console.Clear()` instead of `VSConsole.Console.Clear()` do you get the same error?

I guess I could have the VSConsole library swallow exceptions but if your code is trying to write to the console and the system console doesn't work, having the VSConsole version hide this could suppress bigger underlying issues with the code.

**Comment by hguptauk** [comment] 2022-04-26 23:10
Hi Mrlacey, I created a .net core console application using C# and .NET core 6.0 using visual studio 2022. I am attaching a animated GIF to replicate the issue. Hope this helps. I like your tool very much!
![Error](https://user-images.githubusercontent.com/44865520/165407367-74a7c26c-df8e-42a4-9bb3-c87517e626b6.gif)

Regards,
Hemendr

**Comment by mrlacey** [comment] 2022-04-26 23:28
Which version of Visual Studio 2022 are you using?
Do you get the same error if you call `System.Console.Clear()`?

**Comment by hguptauk** [comment] 2022-04-26 23:53
I got it now!. If you set your console application to Window Application then this issue will happen.
![image](https://user-images.githubusercontent.com/44865520/165410781-40f7e24e-69b6-4761-bb48-6813e04a0eee.png)

Actually I was trying to answer one question on stackoverflow.com using your solution. 
https://stackoverflow.com/questions/3571627/show-hide-the-console-window-of-a-c-sharp-console-application
for that I have to make my console application as windowApplication to hide main console window.
Hope this helps

**Comment by hguptauk** [comment] 2022-04-27 00:03
I have answered the question on stackoverflow.com using your solution
https://stackoverflow.com/questions/2542599/having-the-output-of-a-console-application-in-visual-studio-instead-of-the-conso
Great Work!

**Comment by mrlacey** [comment] 2022-04-27 09:32
> I got it now!. If you set your console application to Window Application then this issue will happen. 

You're trying to use the console when the app doesn't have one. You get the same thing if using the System Console directly.

![image](https://user-images.githubusercontent.com/189547/165483893-bfdde702-efbb-451f-b5bd-e9b050f1bdc0.png)

I hadn't considered anyone trying to use the library (or extension) in an app that isn't a console app so I'm not sure this is a bug but rather it's out of scope.

If you have a good argument for having this work with non-console apps (such as as a way to have an alternative to standard debug output) I'd be happy to reopen this issue (or create a new one) and discuss the scenario further.

**Closed as completed by mrlacey** 2022-04-27 09:32 UTC

**Comment by hguptauk** [comment] 2022-04-27 10:33
Basically I want to achieve two things in my console application
 - redirect console output to some window that is integrated inside visual studio like VSConsole
 - hide the main console window because I don't need it any more as I am getting same output from VSConsole.
Now in order to hide the main console window I changed my application type property from console application to window application, but application still behave as console application.
https://stackoverflow.com/questions/3571627/show-hide-the-console-window-of-a-c-sharp-console-application.

**Comment by mrlacey** [comment] 2022-04-27 10:58
> Basically I want to achieve two things in my console application
> 
> * redirect console output to some window that is integrated inside visual studio like VSConsole
> * hide the main console window because I don't need it any more as I am getting same output from VSConsole.
>   Now in order to hide the main console window I changed my application type property from console application to window application, but application still behave as console application.
>   https://stackoverflow.com/questions/3571627/show-hide-the-console-window-of-a-c-sharp-console-application.

I've created a [new issue](https://github.com/mrlacey/VSConsole/issues/18) to track this as a separate request (rather than a bug)
